In [19]:
import numpy as np
import math as math

# Abstract
Exercice on Deep Learning

In [20]:
def transfer(r):
#     return r if r > 1 else 0
    return math.tanh(r)

In [21]:
def perceptron(m, p):
    r = 0
    # TODO: run it as a matrices product 
    
    for i in range(5):
        for j in range(5):
            r += m[i][j] * p[i][j]
    
    return transfer(r)

In [22]:
def updateWeight(M, weights, alpha, label):
    # Compute the approximations using the perceptron.
    approx = np.array([perceptron(M, weights[0]), perceptron(M, weights[1]), perceptron(M, weights[2])])

    # Compute the errors.
    errs = label - approx

    # Update the weights using the errors made on the matrix and the learning rate.
    weights[0] += M * errs[0] * alpha
    weights[1] += M * errs[1] * alpha
    weights[2] += M * errs[2] * alpha


In [25]:
def train(iters, A, B, C, weights, labels):
    alpha = 0.01
    
    for i in range(iters):
        # Update the weight on the training set
        updateWeight(A, weights, alpha, labels[0])
        updateWeight(B, weights, alpha, labels[1])
        updateWeight(C, weights, alpha, labels[2])
        
        if (i % 500 == 0):
            print(weights[0])

In [47]:
# Initial matrices of dimension 5 x 5 storing 3 images - A, B and C - depicting data to train on.
A = np.array([[1, 0,0,0,0],
            [0, 1,0,0,0],
            [1, 0,1,0,0],
            [0, 0,0,1,0],
            [0, 0,0,0,1]])

B = np.array([[1, 0,0,0,1],
            [0, 1,0,1,0],
            [1, 0,1,0,0],
            [0, 1,0,1,0],
            [1, 0,0,0,1]])

C = np.array([[0, 0,0,0,1],
            [0, 0,0,1,0],             
            [1, 0,1,0,0],
            [0, 1,0,0,0],
            [1, 0,0,0,0]])

# The initial weights defined randomly for each 5 x 5 images.
# A 5 x 5 image has therefore 25 features that need to be weighted. 
# A 5 x 5 weight matrix is used per image.
weights = np.array([np.random.rand(5,5), np.random.rand(5,5), np.random.rand(5,5)])
print(weights[0])
print(weights[1])
print(weights[2])

# Finally the label for each image A = (1,0,0), B = (0,1,0) and C = (0,0,1).
# The labels have been defined upfront and is the expected value that 
# the Neural Network will try to model as close as possible using the weights.
labels = np.array([[1,0,0],
                   [0,1,0],
                   [0,0,1]])

[[1 0 0 0 0]
 [0 1 0 0 0]
 [1 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]
[[0.48779493 0.07534346 0.84368623 0.957497   0.75004553]
 [0.81853995 0.61797005 0.68115007 0.26504472 0.68014459]
 [0.76744616 0.38656426 0.03497428 0.03834802 0.05164136]
 [0.90066369 0.00413463 0.20312149 0.14497022 0.39206359]
 [0.33430406 0.11236223 0.35471249 0.7209308  0.86728549]]
[[0.48003683 0.13982316 0.47540019 0.82859234 0.85196183]
 [0.61572238 0.53177245 0.3291518  0.57027379 0.02848277]
 [0.89871419 0.97305942 0.53177837 0.94626145 0.53562615]
 [0.02369485 0.61558803 0.78604569 0.61110471 0.81362279]
 [0.44608943 0.02385323 0.70658467 0.59374128 0.65433701]]
[[0.43774623 0.45160543 0.27327281 0.82465318 0.58592872]
 [0.24591448 0.43274428 0.28127966 0.75814586 0.44738835]
 [0.20975762 0.05994173 0.53806605 0.95728238 0.96372673]
 [0.14144481 0.77930505 0.63168991 0.81248741 0.78687301]
 [0.25327055 0.71071018 0.62410521 0.70580307 0.44280837]]
[1 0 0]


In [28]:
A * weights[0] * np.ones((5), dtype=np.int16) #* np.ones((5), dtype=np.int16) 

array([[0.6434845 , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.006199  , 0.        , 0.        , 0.        ],
       [0.555235  , 0.        , 0.65179176, 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.65460638, 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.70151033]])

In [29]:
train(5000, A, B, C, weights, labels)

[[ 0.6335175   0.15033192  0.87037025  0.16317523  0.16948393]
 [ 0.45732903 -0.003768    0.36412592  0.80360343  0.3122633 ]
 [ 0.53530896  0.94235925  0.63186572  0.76135429  0.14008227]
 [ 0.94883842  0.25266436  0.10590858  0.64463938  0.65648018]
 [ 0.64163598  0.06299536  0.10096379  0.79624586  0.69154333]]
[[ 0.18620717  0.15033192  0.87037025  0.16317523 -0.64077004]
 [ 0.45732903 -0.45107833  0.36412592 -0.00665054  0.3122633 ]
 [ 0.60167314  0.94235925  0.69822991  0.76135429  0.14008227]
 [ 0.94883842 -0.55758961  0.10590858  0.19732905  0.65648018]
 [-0.16861799  0.06299536  0.10096379  0.79624586  0.244233  ]]
[[ 0.1622429   0.15033192  0.87037025  0.16317523 -0.74800953]
 [ 0.45732903 -0.47504259  0.36412592 -0.11389003  0.3122633 ]
 [ 0.8364624   0.94235925  0.93301917  0.76135429  0.14008227]
 [ 0.94883842 -0.6648291   0.10590858  0.17336479  0.65648018]
 [-0.27585748  0.06299536  0.10096379  0.79624586  0.22026874]]
[[ 0.15462921  0.15033192  0.87037025  0.16317523 -0

In [44]:
print("Label:",labels[0])
print("Approx: ", [perceptron(A, weights[0]), perceptron(A, weights[1]), perceptron(A, weights[2])])

Label: [1 0 0]
Approx:  [0.9917633773838656, 0.0076437280317644945, -0.005616028277755818]


In [45]:
print("Label:",labels[1])
print("Approx: ", [perceptron(B, weights[0]), perceptron(B, weights[1]), perceptron(B, weights[2])])

Label: [0 1 0]
Approx:  [0.007813114377794377, 0.9898436913562886, 0.008019326463989436]


In [46]:
print("Label:",labels[2])
print("Approx: ", [perceptron(C, weights[0]), perceptron(C, weights[1]), perceptron(C, weights[2])])

Label: [0 0 1]
Approx:  [-0.005247049560956765, 0.007184409341876041, 0.9917243156408974]
